// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    user_id, name, bio,
    phone, email, website,
    linkedin, github, twitter, instagram
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, name, bio, phone, email, website, linkedin, github, twitter, instagram, created_at, updated_at
`

type CreateProfileParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	Bio       pgtype.Text `json:"bio"`
	Phone     pgtype.Text `json:"phone"`
	Email     pgtype.Text `json:"email"`
	Website   pgtype.Text `json:"website"`
	Linkedin  pgtype.Text `json:"linkedin"`
	Github    pgtype.Text `json:"github"`
	Twitter   pgtype.Text `json:"twitter"`
	Instagram pgtype.Text `json:"instagram"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.Name,
		arg.Bio,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.Linkedin,
		arg.Github,
		arg.Twitter,
		arg.Instagram,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Linkedin,
		&i.Github,
		&i.Twitter,
		&i.Instagram,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQRToken = `-- name: CreateQRToken :one
INSERT INTO qr_tokens (profile_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, profile_id, token, is_active, expires_at, created_at
`

type CreateQRTokenParams struct {
	ProfileID pgtype.UUID      `json:"profile_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateQRToken(ctx context.Context, arg CreateQRTokenParams) (QrToken, error) {
	row := q.db.QueryRow(ctx, createQRToken, arg.ProfileID, arg.Token, arg.ExpiresAt)
	var i QrToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Token,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createScanLog = `-- name: CreateScanLog :exec
INSERT INTO scan_logs (
    profile_id, device, location, ip_address
)
VALUES ($1, $2, $3, $4)
`

type CreateScanLogParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	Device    pgtype.Text `json:"device"`
	Location  pgtype.Text `json:"location"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateScanLog(ctx context.Context, arg CreateScanLogParams) error {
	_, err := q.db.Exec(ctx, createScanLog,
		arg.ProfileID,
		arg.Device,
		arg.Location,
		arg.IpAddress,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password)
VALUES ($1, $2)
RETURNING id, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableQRToken = `-- name: DisableQRToken :exec
UPDATE qr_tokens
SET is_active = FALSE
WHERE token = $1
`

func (q *Queries) DisableQRToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, disableQRToken, token)
	return err
}

const getProfileByToken = `-- name: GetProfileByToken :one
SELECT p.id, p.user_id, p.name, p.bio, p.phone, p.email, p.website, p.linkedin, p.github, p.twitter, p.instagram, p.created_at, p.updated_at
FROM qr_tokens q
JOIN profiles p ON p.id = q.profile_id
WHERE q.token = $1
AND q.is_active = TRUE
AND (q.expires_at IS NULL OR q.expires_at > NOW())
`

func (q *Queries) GetProfileByToken(ctx context.Context, token string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByToken, token)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Linkedin,
		&i.Github,
		&i.Twitter,
		&i.Instagram,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, name, bio, phone, email, website, linkedin, github, twitter, instagram, created_at, updated_at FROM profiles
WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Linkedin,
		&i.Github,
		&i.Twitter,
		&i.Instagram,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanCount = `-- name: GetScanCount :one
SELECT COUNT(*) FROM scan_logs
WHERE profile_id = $1
`

func (q *Queries) GetScanCount(ctx context.Context, profileID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getScanCount, profileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET name = $2,
    bio = $3,
    phone = $4,
    email = $5,
    website = $6,
    linkedin = $7,
    github = $8,
    twitter = $9,
    instagram = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, bio, phone, email, website, linkedin, github, twitter, instagram, created_at, updated_at
`

type UpdateProfileParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Bio       pgtype.Text `json:"bio"`
	Phone     pgtype.Text `json:"phone"`
	Email     pgtype.Text `json:"email"`
	Website   pgtype.Text `json:"website"`
	Linkedin  pgtype.Text `json:"linkedin"`
	Github    pgtype.Text `json:"github"`
	Twitter   pgtype.Text `json:"twitter"`
	Instagram pgtype.Text `json:"instagram"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Bio,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.Linkedin,
		arg.Github,
		arg.Twitter,
		arg.Instagram,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Linkedin,
		&i.Github,
		&i.Twitter,
		&i.Instagram,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
