// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (user_id, name, bio)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, bio, created_at, updated_at
`

type CreateProfileParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Bio    pgtype.Text `json:"bio"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile, arg.UserID, arg.Name, arg.Bio)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQRToken = `-- name: CreateQRToken :one
INSERT INTO qr_tokens (profile_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, profile_id, token, is_active, expires_at, created_at
`

type CreateQRTokenParams struct {
	ProfileID pgtype.UUID      `json:"profile_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateQRToken(ctx context.Context, arg CreateQRTokenParams) (QrToken, error) {
	row := q.db.QueryRow(ctx, createQRToken, arg.ProfileID, arg.Token, arg.ExpiresAt)
	var i QrToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Token,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createScanLog = `-- name: CreateScanLog :exec
INSERT INTO scan_logs (
    profile_id, device, location, ip_address
)
VALUES ($1, $2, $3, $4)
`

type CreateScanLogParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	Device    pgtype.Text `json:"device"`
	Location  pgtype.Text `json:"location"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateScanLog(ctx context.Context, arg CreateScanLogParams) error {
	_, err := q.db.Exec(ctx, createScanLog,
		arg.ProfileID,
		arg.Device,
		arg.Location,
		arg.IpAddress,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password)
VALUES ($1, $2)
RETURNING id, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles
WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const disableQRToken = `-- name: DisableQRToken :exec
UPDATE qr_tokens
SET is_active = FALSE
WHERE token = $1
`

func (q *Queries) DisableQRToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, disableQRToken, token)
	return err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, user_id, name, bio, created_at, updated_at FROM profiles
WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByToken = `-- name: GetProfileByToken :one
SELECT 
    p.id,
    p.name,
    p.bio,
    

    pc.phone,
    pc.email,
    pc.website,
    pc.linkedin,
    pc.github,
    pc.twitter,
    pc.instagram

FROM qr_tokens q
JOIN profiles p ON p.id = q.profile_id
LEFT JOIN profile_contacts pc ON pc.profile_id = p.id

WHERE q.token = $1
AND q.is_active = TRUE
AND (q.expires_at IS NULL OR q.expires_at > NOW())
`

type GetProfileByTokenRow struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Bio       pgtype.Text `json:"bio"`
	Phone     pgtype.Text `json:"phone"`
	Email     pgtype.Text `json:"email"`
	Website   pgtype.Text `json:"website"`
	Linkedin  pgtype.Text `json:"linkedin"`
	Github    pgtype.Text `json:"github"`
	Twitter   pgtype.Text `json:"twitter"`
	Instagram pgtype.Text `json:"instagram"`
}

func (q *Queries) GetProfileByToken(ctx context.Context, token string) (GetProfileByTokenRow, error) {
	row := q.db.QueryRow(ctx, getProfileByToken, token)
	var i GetProfileByTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Linkedin,
		&i.Github,
		&i.Twitter,
		&i.Instagram,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, name, bio, created_at, updated_at FROM profiles
WHERE user_id = $1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileContacts = `-- name: GetProfileContacts :one
SELECT profile_id, phone, email, website, linkedin, github, twitter, instagram, created_at, updated_at FROM profile_contacts
WHERE profile_id = $1
`

func (q *Queries) GetProfileContacts(ctx context.Context, profileID pgtype.UUID) (ProfileContact, error) {
	row := q.db.QueryRow(ctx, getProfileContacts, profileID)
	var i ProfileContact
	err := row.Scan(
		&i.ProfileID,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Linkedin,
		&i.Github,
		&i.Twitter,
		&i.Instagram,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScanCount = `-- name: GetScanCount :one
SELECT COUNT(*) FROM scan_logs
WHERE profile_id = $1
`

func (q *Queries) GetScanCount(ctx context.Context, profileID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getScanCount, profileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getScanLogsByProfile = `-- name: GetScanLogsByProfile :many
SELECT id, profile_id, scanned_at, device, location, ip_address FROM scan_logs
WHERE profile_id = $1
ORDER BY scanned_at DESC
LIMIT $2
`

type GetScanLogsByProfileParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) GetScanLogsByProfile(ctx context.Context, arg GetScanLogsByProfileParams) ([]ScanLog, error) {
	rows, err := q.db.Query(ctx, getScanLogsByProfile, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanLog
	for rows.Next() {
		var i ScanLog
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.ScannedAt,
			&i.Device,
			&i.Location,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET name = $2,
    bio = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, bio, created_at, updated_at
`

type UpdateProfileParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Bio  pgtype.Text `json:"bio"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile, arg.ID, arg.Name, arg.Bio)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfileContacts = `-- name: UpsertProfileContacts :one
INSERT INTO profile_contacts (
    profile_id, phone, email, website,
    linkedin, github, twitter, instagram
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (profile_id) DO UPDATE SET
    phone = EXCLUDED.phone,
    email = EXCLUDED.email,
    website = EXCLUDED.website,
    linkedin = EXCLUDED.linkedin,
    github = EXCLUDED.github,
    twitter = EXCLUDED.twitter,
    instagram = EXCLUDED.instagram,
    updated_at = NOW()
RETURNING profile_id, phone, email, website, linkedin, github, twitter, instagram, created_at, updated_at
`

type UpsertProfileContactsParams struct {
	ProfileID pgtype.UUID `json:"profile_id"`
	Phone     pgtype.Text `json:"phone"`
	Email     pgtype.Text `json:"email"`
	Website   pgtype.Text `json:"website"`
	Linkedin  pgtype.Text `json:"linkedin"`
	Github    pgtype.Text `json:"github"`
	Twitter   pgtype.Text `json:"twitter"`
	Instagram pgtype.Text `json:"instagram"`
}

func (q *Queries) UpsertProfileContacts(ctx context.Context, arg UpsertProfileContactsParams) (ProfileContact, error) {
	row := q.db.QueryRow(ctx, upsertProfileContacts,
		arg.ProfileID,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.Linkedin,
		arg.Github,
		arg.Twitter,
		arg.Instagram,
	)
	var i ProfileContact
	err := row.Scan(
		&i.ProfileID,
		&i.Phone,
		&i.Email,
		&i.Website,
		&i.Linkedin,
		&i.Github,
		&i.Twitter,
		&i.Instagram,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
