// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateQRToken(ctx context.Context, arg CreateQRTokenParams) (QrToken, error)
	CreateScanLog(ctx context.Context, arg CreateScanLogParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DisableQRToken(ctx context.Context, token string) error
	GetProfileByToken(ctx context.Context, token string) (Profile, error)
	GetProfileByUserID(ctx context.Context, userID pgtype.UUID) (Profile, error)
	GetScanCount(ctx context.Context, profileID pgtype.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
}

var _ Querier = (*Queries)(nil)
